version: '3'

networks:
 admin-net:
  driver: bridge

services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_HOT=false
    networks:
      - admin-net
    ports:
      - "3000:3000"
    # 其他选项...

  backend:
    build:
      context: ./backend/server
      args:
        - http_proxy=http://host.docker.internal:7890
        - https_proxy=http://host.docker.internal:7890
    networks:
      - admin-net
    ports:
      - "5004:5004"
    # 其他选项...
