from get_bars_data import get_bars_by_type, get_bars
from draw_hl_points import draw_hl_points
from szss_stock import draw_szss_stock

def draw_other_stock():
    draw_hl_points(get_bars_by_type(symbol="0700.HK", type="stock"))

    draw_hl_points(get_bars_by_type(symbol="6501.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="6702.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="9984.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="6758.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="7203.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="8035.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="7201.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="2282.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="8058.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="6752.T", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="4506.T", type="stock"))

    draw_hl_points(get_bars_by_type(symbol="NVDA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NFLX", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ACHC", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ATVI", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ADBE", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AMD", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ARLP", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="GOOGL", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AMZN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AAL", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AMGN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AAPL", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AMAT", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ASUR", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ATRA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="BIDU", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="BIDU", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="BZUN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="BIIB", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="BKNG", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="GTLS", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CTAS", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CSCO", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CME", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CME", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CMCSA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="COMM", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CORT", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="COST", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="CRON", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="DBX", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="DBX", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="EBAY", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="EA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ENTG", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="EXPE", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="META", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="FANH", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="GILD", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="GRPN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="INTC", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="IOVA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="IQ", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="JD", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="KHC", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="LRCX", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="LULU", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="MLCO", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="MU", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="MSFT", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="MOMO", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NDAQ", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="FIZZ", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NKTR", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NTAP", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NTES", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NMRK", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="NWSA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="OSTK", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="PYPL", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="PEP", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="PDD", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="QCOM", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ROKU", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="SOHU", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="SONO", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="SBUX", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="TSLA", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="TLRY", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="UXIN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="WB", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="WDC", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="WYNN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="YY", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="Z", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ZS", type="stock"))

    draw_hl_points(get_bars_by_type(symbol="MMM", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="ACN", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="A", type="stock"))
    draw_hl_points(get_bars_by_type(symbol="AEM", type="stock"))
    # TODO:

    draw_hl_points(get_bars_by_type(symbol="ES=F", type="stock index"))
    draw_hl_points(get_bars_by_type(symbol="YM=F", type="stock index"))
    draw_hl_points(get_bars_by_type(symbol="^GDAXI", type="stock index"))
    draw_hl_points(get_bars_by_type(symbol="^RUT", type="stock index"))
    draw_hl_points(get_bars_by_type(symbol="^N225", type="stock index"))

    draw_hl_points(get_bars_by_type(symbol="FAZ", type="etf", symbol_title="FIN BEAR 3X ETF"))

def draw_other_goods():
    draw_hl_points(get_bars_by_type(symbol="GC=F", type="goods"))
    draw_hl_points(get_bars_by_type(symbol="SI=F", type="goods"))
    draw_hl_points(get_bars_by_type(symbol="CL=F", type="goods"))
    draw_hl_points(get_bars_by_type(symbol="BZ=F", type="goods"))
    draw_hl_points(get_bars_by_type(symbol="HO=F", type="goods"))
    draw_hl_points(get_bars_by_type(symbol="HG=F", type="goods"))
    draw_hl_points(get_bars_by_type(symbol="CT=F", type="goods"))

def draw_currency():
    draw_hl_points(get_bars_by_type(symbol="EURUSD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPUSD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="AUDUSD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="NZDUSD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CNH=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CAD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="JPY=X", type="currency"))
    # draw_hl_points(get_bars_by_type(symbol="TRY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="HKD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="SGD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="INR=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="MXN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="ZAR=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="SEK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="NOK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="DKK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="RUB=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="PLN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="HUF=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="THB=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CZK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="ILS=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="RON=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="BRL=X", type="currency"))


    draw_hl_points(get_bars_by_type(symbol="EURJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="EURJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CHFJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CNHJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="AUDJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CADJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="NZDJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="NOKJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="HKDJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="SGDJPY=X", type="currency"))
    # draw_hl_points(get_bars_by_type(symbol="TRYJPY=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="ZARJPY=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURCHF=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="AUDCHF=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CADCHF=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPCHF=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="NZDCHF=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURGBP=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURSEK=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURCAD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="AUDCAD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPCAD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="NZDCAD=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURAUD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPAUD=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="AUDNZD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="EURNZD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPNZD=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="CHFHUF=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="EURHUF=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="CHFPLN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="AUDPLN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CADPLN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="EURPLN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPPLN=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURRON=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURRUB=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURTRY=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURMXN=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPMXN=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURZAR=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPZAR=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURCZK=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURCNH=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="AUDCNH=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="AUDSGD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="EURSGD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPSGD=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURHKD=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPHKD=X", type="currency"))

    # 次要货币对交叉盘
    draw_hl_points(get_bars_by_type(symbol="AUDNOK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CADNOK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="CHFNOK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="EURNOK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPNOK=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURDKK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPDKK=X", type="currency"))
    # draw_hl_points(get_bars_by_type(symbol="NOKDKK=X", type="currency"))

    draw_hl_points(get_bars_by_type(symbol="EURSEK=X", type="currency"))
    draw_hl_points(get_bars_by_type(symbol="GBPSEK=X", type="currency"))
    # draw_hl_points(get_bars_by_type(symbol="NOKSEK=X", type="currency"))

def draw_cryptos():
    draw_hl_points(get_bars_by_type(symbol="1INCH-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AAVE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ACH-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ADA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AGIX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AGLD-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ALGO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ALICE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ALPHA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AMB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ANKR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ANT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="APE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="API3-USD", type="cryptos"))
    # draw_hl_points(get_bars_by_type(symbol="APT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ARB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ARKM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ARPA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ASTR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ATA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ATOM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AUDIO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AVAX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="AXS-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BAKE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BAL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BAND-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BAT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BCH-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BEL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BLUR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BLZ-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BNB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="BNX-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="BTC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="C98-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CELO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CELR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CFX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CHR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CHZ-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CKB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="COMBO-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="COTI-USD", type="cryptos"))
    # draw_hl_points(get_bars_by_type(symbol="CRV-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="CTSI-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="CVX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DAR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DASH-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="DENT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DGB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DODO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DOGE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DOT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DUSK-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="DYDX-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="EGLD-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ENJ-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ENS-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="EOS-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ETC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ETH-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="FET-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="FIL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="FLM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="FLOW-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="FTM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="FXS-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="GALA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="GAL-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="GTC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="HBAR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="HIGH-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="HOOK-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="HOT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ICP-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ICX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="IDEX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ID-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="INJ-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="IOST-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="IOTX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="JASMY-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="JOE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="KAVA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="KEY-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="KLAY-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="KNC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="KSM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LDO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LEVER-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LINA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LINK-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LIT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LPT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LQTY-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LRC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="LTC-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="MANA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="MATIC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="MAV-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="MDT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="MINA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="MKR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="MTL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="NEAR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="NEO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="NKN-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="NMR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="OCEAN-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="OGN-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="OMG-USD", type="cryptos"))
    # draw_hl_points(get_bars_by_type(symbol="ONE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ONT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="OP-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="PENDLE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="PEOPLE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="PERP-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="PHB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="QNT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="QTUM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RAD-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RDNT-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="REEF-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="REN-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RLC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RNDR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ROSE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RSR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RUNE-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="RVN-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SAND-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SFP-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SKL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SNX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SOL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SPELL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SSV-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="STMX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="STORJ-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="STX-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SUI-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SUSHI-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="SXP-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="THETA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="TLM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="TOMO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="TRB-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="TRU-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="TRX-USD", type="cryptos"))

    draw_hl_points(get_bars_by_type(symbol="T-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="UMA-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="UNFI-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="VET-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="WAVES-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="WLD-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="WOO-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XEM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XLM-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XMR-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XRP-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XTZ-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XVG-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="XVS-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="YFI-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ZEC-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ZEN-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ZIL-USD", type="cryptos"))
    draw_hl_points(get_bars_by_type(symbol="ZRX-USD", type="cryptos"))


draw_cryptos()
draw_currency()
draw_other_stock()
draw_other_goods()
draw_szss_stock()
